# task: automatic-speech-recognition
task: asr
base_model: facebook/wav2vec2-base-960h
project_name: autotrain-asr-project
log: tensorboard
backend: local 

data:
  dataset_name: Prajwal-143/ASR-Tamil-cleaned # Name of the dataset on the Hugging Face Hub
  config_name: clean
  train_split: train.100
  valid_split: validation
  column_mapping:
    audio_column: path      # Matches LibriSpeech
    text_column: sentence       # Matches LibriSpeech
params:
  epochs: 10
  batch_size: 16
  lr: 3e-4
  optimizer: adamw_torch
  scheduler: linear
  mixed_precision: fp16
  gradient_accumulation: 2
  warmup_steps: 500
  max_steps: 10000
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  eval_strategy: steps
  save_steps: 500
  eval_steps: 500
  logging_steps: 50
  load_best_model_at_end: true
  metric_for_best_model: wer
  greater_is_better: false
  group_by_length: true
  fp16: true
  gradient_checkpointing: true
  save_total_limit: 3

hub:
  username: mathur
  token: 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
  push_to_hub: true
# base_model: facebook/wav2vec2-base-960h
# project_name: autotrain-asr-project
# log: tensorboard
# backend: hub

# data:
#   dataset_name: librispeech_asr # Name of the dataset on the Hugging Face Hub
#   config_name: clean # Configuration for the dataset
#   train_split: train.100 # Name of the training split
#   valid_split: validation # Name of the validation split
#   column_mapping:
#     audio_column: path
#     text_column: sentence
# params:
#   epochs: 10
#   batch_size: 16
#   lr: 3e-4
#   optimizer: adamw_torch
#   scheduler: linear
#   mixed_precision: fp16
#   gradient_accumulation: 2
#   warmup_steps: 500
#   max_steps: 10000
#   per_device_train_batch_size: 16
#   per_device_eval_batch_size: 16
#   eval_strategy: steps
#   save_steps: 500
#   eval_steps: 500
#   logging_steps: 50
#   load_best_model_at_end: true
#   metric_for_best_model: wer
#   greater_is_better: false
#   group_by_length: true
#   fp16: true
#   gradient_checkpointing: true
#   save_total_limit: 3

# hub:
#   username: ${HF_USERNAME}
#   token: ${HF_TOKEN}
#   push_to_hub: true