task: automatic-speech-recognition
base_model: facebook/wav2vec2-base-960h
project_name: autotrain-asr-project
log: tensorboard
backend: local

data:
  path: data/ # Path to the directory containing the train and valid files
  train_split: train # This must be either train.csv or train.json
  valid_split: valid # This must be either valid.csv or valid.json
  column_mapping:
    audio_path_column: audio_path # Name of the column containing the audio file paths
    audio_column: audio
    text_column: sentence # Name of the column containing the transcriptions

params:
  epochs: 10
  batch_size: 16
  lr: 3e-4
  optimizer: adamw_torch
  scheduler: linear
  mixed_precision: fp16
  gradient_accumulation: 2
  warmup_steps: 500
  max_steps: 10000
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  eval_strategy: steps
  save_steps: 500
  eval_steps: 500
  logging_steps: 50
  load_best_model_at_end: true
  metric_for_best_model: wer
  greater_is_better: false
  group_by_length: true
  fp16: true
  gradient_checkpointing: true
  save_total_limit: 3

hub:
  username: ${HF_USERNAME}
  token: ${HF_TOKEN}
  push_to_hub: true